---
language: sh
services:
  - docker

before_install:
  - sudo apt-get update -qq

addons:
  apt:
    packages:
      - sshpass

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  #- sudo ln -s $PWD/test/support/bats/bin/bats /usr/local/bin

install:

script:
  - bats test/*.bats

notifications:
  # webhooks: https://galaxy.ansible.com/api/notifications/
