#!/bin/sh
#vim: set ft=shell
# USAGE:
#   $ sh -c "`curl -fsSL https://raw.githubusercontent.com/paulopatto/dotfiles/master/bin/install.sh`"
if[-d "$HOME/.rvm"]; then
  echo 'Install RVM'
  curl -sSL https://get.rvm.io | bash -s stable --ruby --gems=pry
fi


if[!-d "$HOME/.dotfiles"]; then
  echo 'Install .dotfiles'

  git clone https://github.com/paulopatto/dotfiles.git "$HOME/.dotfiles"
  cd "$HOME/.dotfiles"

  rake install
else
  echo '.dotfiles is already installed'
fi
