#!/bin/bash
# vim: set ft=sh :

FILE=$1

if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
  BRANCH_NAME=${BASH_REMATCH[1]}
  test "$branch" != master || branch=' '
else
  # Detached HEAD.  (branch=HEAD is a faster alternative.)
  BRANCH_NAME="`git describe --all --contains --abbrev=4 HEAD 2> /dev/null || echo HEAD`"
fi

echo $1

if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "master" ]; then
  sed -i -e '1s@^@['"$BRANCH_NAME"']: @' $FILE
fi
