---
- name: "Download JMeter"
  get_url:
    url:      "http://ftp.unicamp.br/pub/apache//jmeter/binaries/apache-jmeter-5.0.tgz"
    dest:     "/tmp"
    checksum: "sha512:https://www.apache.org/dist/jmeter/binaries/apache-jmeter-5.0.tgz.sha512"

- name: "Extract JMeter"
  unarchive:
    src: "/tmp/apache-jmeter-5.0.tgz"
    dest: "/opt"

