---
- name: Install Ubuntu libs
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - ncurses-term
    - exuberant-ctags
    - libjemalloc1
    - libjemalloc-dev
  become: true
