---
- name: "Install NeoVim via DNF"
  become: true
  dnf:
    state: present
    name:
      - nodejs
      - npm
      - git
      - neovim
  when:
    - ansible_distribution == "Fedora"

- name: "Install NeoVim via APT"
  become: true
  apt:
    state: present
    name:
      - nodejs
      - npm
      - git
      - neovim
  when:
    - ansible_distribution == "Ubunutu"

- name: "Create nvim autoload dir"
  file:
    path: "~/.local/share/nvim/site/autoload"
    state: directory

- name: "Create nvim config dir"
  file:
    path: "~/.config/nvim"
    state: directory

- name: "Install Vim Plug"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.local/share/nvim/site/autoload/plug.vim"

- name: "NeoVim config file (init.vim)"
  template:
    src: init.vim
    dest: "~/.config/nvim/init.vim"
  notify: nvim_plug_install
