---
- name: "Install NeoVim via DNF"
  become: true
  dnf:
    state: present
    name:
      - nodejs
      - npm
      - git
      - neovim
  when:
    - ansible_distribution == "Fedora"
  tags:
    - install
    - bootstrap

- name: "Install NeoVim via APT"
  become: true
  apt:
    state: present
    name:
      - nodejs
      - npm
      - git
      - neovim
  when:
    - ansible_distribution == "Ubunutu"
  tags:
    - install
    - bootstrap

- name: "Create nvim autoload dir"
  file:
    path: "{{ansible_env.HOME}}/.local/share/nvim/site/autoload"
    state: directory
  tags:
    - config
    - bootstrap

- name: "Create nvim config dir"
  file:
    path: "{{ansible_env.HOME}}/.config/nvim"
    state: directory
  tags:
    - config
    - bootstrap

- name: "Install Vim Plug"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ansible_env.HOME}}/.local/share/nvim/site/autoload/plug.vim"
  tags:
    - install
    - bootstrap

- name: "NeoVim config file (init.vim)"
  template:
    src: init.vim
    dest: "{{ansible_env.HOME}}/.config/nvim/init.vim"
  tags:
    - config
    - bootstrap
  notify: 
    - nvim_plug_install
