# Path to your oh-my-zsh installation.
export SHELL=/bin/zsh
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="awesome-fontconfig"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs)

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git ruby rails pip zsh-syntax-highlighting)

# User configuration

export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export EDITOR='vim'
export TERM='xterm-256color' # old: 'screen-256color'
export PAGER='less -rS' # By @dlisboa

############################################
########          GIT
############################################
export GITCONFIG=$HOME/.gitconfig
export GITIGNORE=$HOME/.gitignore_global

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


###############
# ssh
###############
export SSH_KEY_PATH="~/.ssh/dsa_id"
export SSHKEY="cat $HOME/.ssh/id_rsa.pub"

#Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

##################################
#### CONFIGS FILES
##################################
alias zshconfig="$EDITOR $HOME/.zshrc"
alias vimconfig="$EDITOR $HOME/.vim/vimrc"
alias tmuxconfig="$EDITOR $HOME/.tmux.conf"
alias ohmyzshconfig="$EDITOR $HOME/.oh-my-zsh"
alias gitconfig="$EDITOR $HOME/.gitconfig"

############################
# MySQL Commands on CentOS
############################
# alias startmysql="systemctl start mysqld"
# alias stopmysql="systemctl stop mysqld"
# alias restartmysq="systemctl restart mysqld"
# alias mysqlstatus="systemctl status mysqld"


#######################
# ElasticSearch [ELK]
######################
# if elasticsearch &> /dev/null ; then
#   export ES_HOME='/opt/elasticsearch-5.2.1'
#   alias elkconfig="$EDITOR $ES_HOME/config/elasticsearch.yml"
# fi

alias cless="pygmentize -g $1 | less -N"

export PATH=$HOME/miniconda3/bin:$PATH
export ANDROID_HOME=/opt/android_sdk

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Configs to ASDF-VM:
source /home/paulopatto/.asdf/asdf.sh
source /home/paulopatto/.asdf/completions/asdf.bash
# End of ASDF-VM

