name: "Build paulopatto/dotfiles w/ Ansible"
description: "Collection of scripts to config my laptops and machines"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install nodejs 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install -g bats
      - iun: bats test/*.bats
